-- Insert 2021 Expansion Phase timeline entries
INSERT INTO public.timeline_content (year, year_title, month, title, content, highlight, icon_name, gradient_class, display_order, is_active) VALUES
(2021, 'Expansion Phase', '', 'MANA Surge & Meta Backlash', 'As MANA surged and Facebook became Meta, Decentraland gained visibility. The DAO grew fast, and the community exploded with new members.', 'Metaverse Hype', 'Zap', 'from-yellow-500 to-red-600', 6, true),
(2021, 'Expansion Phase', '', 'Free Building Giveaway', 'I released 3 prefab buildings for free to help populate the map. They were downloaded heavily and can still be found in-world today.', 'Open Access', 'Building', 'from-green-400 to-blue-500', 7, true),
(2021, 'Expansion Phase', '', 'Modular Architecture', 'Created a modular building system with downloadable components. Great idea, but too technical for mass adoption at the time.', 'Modular System', 'Cpu', 'from-teal-500 to-cyan-600', 8, true),
(2021, 'Expansion Phase', '', 'Swiss on YouTube', 'Started a modest YouTube channel to share metaverse insights and boost visibility. Low production, but the message connected.', 'First Videos', 'Users', 'from-blue-500 to-purple-600', 9, true),
(2021, 'Expansion Phase', '', 'Metaverse VTuber Moment', 'Used my Decentraland avatar in a YouTube video — likely the first crypto/metaverse VTuber crossover. It got real attention.', 'VTuber First', 'Sparkles', 'from-pink-500 to-yellow-500', 10, true),
(2021, 'Expansion Phase', '', 'Ecosystem Promotion', 'Recorded interviews with creators to spotlight Decentraland during its peak. Tried to give visibility to the real builders.', 'Community Voice', 'Globe', 'from-purple-600 to-indigo-600', 11, true),
(2021, 'Expansion Phase', '', 'Mentioned in Handbook', 'My VTuber work was mentioned in The Metaverse Handbook — a small but symbolic moment that Swiss had left a trace.', 'Recognized', 'Star', 'from-yellow-400 to-orange-500', 12, true),
(2021, 'Expansion Phase', '', 'NFT Mania Hits DCL', 'NFT trading hit insane levels. Decentraland''s wearables and land flipped fast. DCL became tightly linked with NFT culture.', 'NFT Peak', 'Crown', 'from-pink-600 to-red-500', 13, true),
(2021, 'Expansion Phase', '', 'Casino & P2E Strategy', 'Invested in DCL casino wearables, then pivoted into Web3 games to build a guild and earn revenue from play-to-earn models.', 'Gaming Shift', 'Target', 'from-blue-600 to-green-500', 14, true),
(2021, 'Expansion Phase', '', 'The White Jacket', 'Acquired one of only 10 legendary white jackets — an L1 wearable that became my signature look across platforms.', 'Signature Item', 'Trophy', 'from-gray-500 to-white', 15, true);