// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cevahjgzsjuyrtxiihth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNldmFoamd6c2p1eXJ0eGlpaHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDY4NTcsImV4cCI6MjA2ODU4Mjg1N30.pJRZqtuAmbHiYbWxlGWAWzAs_ZcsBPQzcFn29zKDKS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});